### ISSUE TITLE
These jokes are lame

### ISSUE THREAD

**Issue by tylergets** [llcoole93/spring-chuck-norris#1]
Evan can come up with better jokes, this app sucks

**Comment by llcoole93** [comment]
....................../´¯/) 
....................,/¯../ 
.................../..../ 
............./´¯/'...'/´¯¯`·¸ 
........../'/.../..../......./¨¯\ 
........('(...´...´.... ¯~/'...') 
.........\.................'...../ 
..........''...\.......... _.·´ 
............\..............( 
..............\.............\...

**Comment by llcoole93** [comment]
youre damn right i can
